# Generated by Django 5.0.2 on 2024-08-23 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linerCRM', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pago',
            name='recibo_pdf',
            field=models.FileField(blank=True, null=True, upload_to='recibos/'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='rol',
            field=models.CharField(choices=[('Secretaria', 'Secretaria'), ('Superadmin', 'Superadmin')], default='Secretaria', max_length=30),
        ),
    ]
