# Generated by Django 5.0.2 on 2024-09-01 21:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linerCRM', '0002_pago_recibo_pdf_alter_customuser_rol'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstalacionDeServicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_instalacion', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instalaciones', to='linerCRM.cliente')),
                ('tecnico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instalaciones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Instalación de Servicio',
                'verbose_name_plural': 'Instalaciones de Servicio',
            },
        ),
    ]
